[build]
    publish="dist/"
    command="npm run build"
[build]
    command="mv ./src/components/landing/face/scene.json ./dist/scene.json"
[[redirects]]
    from="/assets/scene.json"
    to="/src/components/landing/face/scene.json"